 const Productdata = [
    {
        "title": "Leather Straps Wristwatch",
        "description": "Style: Sport , Clasp: Buckles , Water Resistance Depth:3Bar",
        "image": "https://i.dummyjson.com/data/products/61/3.jpg",
        "category": "watches",
        "size": "S",
        "color": "Gold",
        "price": 120,

    },
    {
        "title": "Waterproof Leather Brand Watch",
        "description": "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
        "image": "https://i.dummyjson.com/data/products/62/2.jpg",
        "category": "watches",
        "size": "L",
        "color": "Brown",
        "price": 46,
    },
    {
        "title": "Royal Blue Premium Watch",
        "description": "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
        "image": "https://i.dummyjson.com/data/products/63/thumbnail.webp",
        "category": "watches",
        "size": "M",
        "color": "Blue",
        "price": 50,

    },
    {
        "title": "Leather Strap Skeleton Watch",
        "description": "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
        "image": "https://i.dummyjson.com/data/products/64/3.jpg",
        "category": "watches",
        "size": "L",
        "color": "Blue",
        "price": 46,
    },
    {
        "title": "Stainless Steel Wrist Watch",
        "description": "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
        "image": "https://i.dummyjson.com/data/products/65/1.jpg",
        "category": "watches",
        "size": "L",
        "color": "Gold",
        "price": 47,

    }
    ,
    {
        "title": "Steel Analog Couple Watches",
        "description": "Elegant design, Stylish ,Unique & Trendy,Comfortable wear",
        "image": "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
        "category": "watches",
        "size": "L",
        "color": "Gold",
        "price": 35,

    },
    {
        "title": "Fashion Magnetic Wrist Watch",
        "description": "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
        "image": "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
        "category": "watches",
        "size": "L",
        "color": "Bronze",
        "price": 60,

    },
    {
        "title": "Stylish Luxury Digital Watch",
        "description": "Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls",
        "image": "https://i.dummyjson.com/data/products/69/4.jpg",
        "category": "watches",
        "size": "L",
        "color": "Gold",
        "price": 57,

    },
    {
        "title": "Golden Watch Pearls Bracelet Watch",
        "description": "Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women",
        "image": "https://i.dummyjson.com/data/products/69/2.jpg",
        "category": "watches",
        "size": "L",
        "color": "Gold",
        "price": 47,

    },
    {
        "title": "Stainless Steel Women",
        "description": "Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies",
        "image": "https://i.dummyjson.com/data/products/70/2.jpg",
        "category": "watches",
        "size": "L",
        "color": "Silver",
        "price": 35,

    }
    ,
    {
        "title": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
        "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
        "category": "men",
        "image": "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
        "size": "L",
        "color": "Blue",
        "price": 109.95,
    },
    {
        "title": "Mens Casual Premium Slim Fit T-Shirts ",
        "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
        "size": "S",
        "color": "White",
        "price": 22.3,
    },
    {
        "title": "Mens Cotton Jacket",
        "description": "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
        "size": "M",
        "color": "Brown",
        "price": 55.99,

    },
    {
        "title": "Mens Casual Slim Fit",
        "description": "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
        "size": "L",
        "color": "Blue",
        "price": 15.99,
    },
    {
        "title": "half sleeves T shirts",
        "description": "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
        "category": "men",
        "image": "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
        "size": "S",
        "color": "Blue",
        "price": 23,
    },
    {
        "title": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
        "price": 109.95,
        "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
        "category": "men",
        "image": "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
        "size": "M",
        "color": "Blue",
    },
    {
        "title": "Mens Casual Premium Slim Fit T-Shirts ",
        "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
        "size": "L",
        "color": "White",
        "price": 22.3,
    },
    {
        "title": "Mens Cotton Jacket",
        "description": "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
        "size": "S",
        "color": "Brown",
        "price": 55.99,
    },
    {
        "title": "Mens Casual Slim Fit",
        "description": "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
        "size": "M",
        "color": "Blue",
        "price": 15.99,
    },
    {
        "title": "half sleeves T shirts",
        "description": "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
        "category": "mens",
        "image": "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
        "size": "L",
        "color": "Blue",
        "price": 23,
    },

    {
        "title": "Mens Cotton Jacket",
        "description": "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
        "size": "S",
        "color": "Brown",
        "price": 55.99,

    },

    {
        "title": "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
        "description": "Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
        "category": "women",
        "image": "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
        "size": "L",
        "color": "Purple",
        "price": 56.99,

    },
    {
        "title": "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
        "description": "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
        "category": "women",
        "image": "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
        "size": "M",
        "color": "Black",
        "price": 29.95,
    },
    {
        "title": "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
        "description": "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
        "category": "women",
        "image": "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
        "size": "L",
        "color": "Black",
        "price": 29.95,

    },
    {
        "title": "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
        "description": "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
        "category": "women",
        "image": "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
        "size": "L",
        "color": "Blue",
        "price": 29.95,

    },
    {
        "title": "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
        "description": "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
        "category": "women",
        "image": "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
        "size": "L",
        "color": "Blue",
        "price": 39.99,

    },
    {
        "title": "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
        "description": "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
        "category": "women",
        "image": "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
        "size": "L",
        "color": "Blue",
        "price": 39.99,

    },
    {
        "title": "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
        "description": "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
        "category": "women",
        "image": "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
        "size": "L",
        "color": "Blue",
        "price": 39.99,

    },
    {
        "title": "MBJ Women's Solid Short Sleeve Boat Neck V ",
        "description": "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
        "category": "women",
        "image": "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
        "size": "L",
        "color": "White",
        "price": 9.85,

    },
    {
        "title": "Opna Women's Short Sleeve Moisture",
        "description": "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
        "category": "women",
        "image": "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
        "size": "L",
        "color": "Red",
        "price": 7.95,

    },
    {
        "title": "DANVOUY Womens T Shirt Casual Cotton Short",
        "description": "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
        "category": "women",
        "image": "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
        "size": "L",
        "color": "Purple",
        "price": 12.99,

    }

    ,
    {
        "title": "Nike",
        "description": "Nike shoes are a type of shoe that are designed to be worn while performing athletic activities. They are designed to be flexible, durable, and provide maximum comfort.",
        // "image": "https://api.lorem.space/image/shoes?w=640&h=480&r=3957",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/alexander-rotker-l8p1aWZqHvE-unsplash.jpg",
        "size": "L",
        "color": "Blue",
        "price": 535,


    },
    {
        "title": "Designed Shoes",
        "description": "Designed shoes are a type of shoe that are designed to be worn in party. ",
        // "image": "https://api.lorem.space/image/shoes?w=640&h=480&r=2447",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
        "size": "L",
        "color": "White",
        "price": 249,
    },

    {
        "title": "Nike",
        "description": "Nike shoes are a type of shoe that are designed to be worn while performing athletic activities. They are designed to be flexible, durable, and provide maximum comfort.",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/revolt-164_6wVEHfI-unsplash.jpg",
        "size": "L",
        "color": "Red",
        "price": 386,
    },
    {
        "title": "Nike",
        "description": "Nike shoes are a type of shoe that are designed to be worn while performing athletic activities. They are designed to be flexible, durable, and provide maximum comfort.",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/alex-motoc-xyjB6_ZDaKw-unsplash.jpg",
        "size": "L",
        "color": "Brown",
        "price": 742,
    },
    {
        "title": "Nike",
        "description": "Nike shoes are a type of shoe that are designed to be worn while performing athletic activities. They are designed to be flexible, durable, and provide maximum comfort.",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/matthew-dagelet-tBdkpxj3A7Q-unsplash.jpg",
        "size": "L",
        "color": "Orange",
        "price": 184,
    },
    {
        "title": "Vans",
        "description": "Vans is the original action sports footwear company rooted in authenticity and creativity. Founded in 1966, Vans has thrived on a legacy of impacting our greater community through Vans' four pillars: action sports, music, art and street culture.",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/paul-gaudriault-a-QH9MAAVNI-unsplash.jpg",
        "size": "L",
        "color": "Maroon",
        "price": 747,
    },
    {
        "title": "Vans",
        "description": "Vans is the original action sports footwear company rooted in authenticity and creativity. Founded in 1966, Vans has thrived on a legacy of impacting our greater community through Vans' four pillars: action sports, music, art and street culture.",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/mojtaba-fahiminia-t4g1gctAaKk-unsplash.jpg",
        "size": "L",
        "color": "White",
        "price": 950,
    },
    {
        "title": "Adidas",
        "description": "Adidas is a global brand known for its sports shoes, clothing, and accessories. The company was founded in 1949 by Adolf Dassler, who originally produced his shoes in his mother's basement in Herzogenaurach, Germany. Adidas is now a global sports brand and an industry leader in sports performance products",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/daniel-storek-JM-qKEd1GMI-unsplash.jpg",
        "size": "L",
        "color": "White",
        "price": 908,
    },
    {
        "title": "Adidas",
        "description": "Adidas is a global brand known for its sports shoes, clothing, and accessories. The company was founded in 1949 by Adolf Dassler, who originally produced his shoes in his mother's basement in Herzogenaurach, Germany. Adidas is now a global sports brand and an industry leader in sports performance products",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/daniel-storek-JM-qKEd1GMI-unsplash.jpg",
        "size": "L",
        "color": "White",
        "price": 301,
    },
    {
        "title": "Nike Black",
        "description": "Nike shoes are a type of shoe that are designed to be worn while performing athletic activities. They are designed to be flexible, durable, and provide maximum comfort.",
        "category": "shoes",
        "image": "https://cdn.lorem.space/images/shoes/.cache/640x480/andres-jasso-PqbL_mxmaUE-unsplash.jpg",
        "size": "L",
        "color": "Black",
        "price": 349,
    },
]

module.exports =Productdata;